name: maanecommerceui
description: An E-Commerce App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  flutter_easyloading: ^3.0.5
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  flutter_stripe: ^10.0.0
  http: ^1.1.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "images/96x96.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: MNCustomIcons
      fonts:
        - asset: fonts/MNCustomIcons.ttf
